config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :companies
  resources :cash_transactions, only: %i[create destroy]

  get 'profile', to: 'user_panel#profile', as: :profile
  get '/edit_profile', to: 'user_panel#edit_profile', as: :edit_profile
  devise_for :users,
             controllers: { sessions: 'users/sessions',
                            registrations: 'users/registrations',
                            passwords: 'users/passwords',
                            invitations: 'users/invitations' }
  resources :users, only: %i[edit update]

  authenticated :user, ->(user) { user.has_role? :teacher } do
    root 'user_panel#profile'
  end

  authenticated :user, ->(user) { user.has_role? :student } do
    root 'companies#index'
  end
  devise_scope :user do
    root to: 'users/sessions#new'
  end
end

app/controllers/user_panel_controller.rb
# frozen_string_literal: true

# :User Panel Controller:
class UserPanelController < ApplicationController
  load_and_authorize_resource class: false
end

app/views/user_panel/edit_profile.html.erb
<div class="container-fluid container-top">
	<div class="container container-signin container-sign">
		<div class="modal-login-body">
			<h3 class="text-center">Update Profile</h3>
			<%= form_for(current_user) do |f| %>
				<div class="form-group mt-3">
					<label for="name">Name</label>
					<%= f.text_field :name, autofocus: true,required: true, placeholder: 'Enter Your Name', class: 'form-control login-form', required: true %>
				</div>
				<div class="actions mt-3">
					<%= f.submit "Update", class: 'btn btn-primary btn-lg btn-block mb-3 btn-submit' %>
					<%= link_to "Dashboard",companies_path,class: "btn btn-secondary btn-lg btn-block btn-submit mb-3 "%>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/user_panel/profile.html.erb
<div class="container container-dashboard">
  <div class="row">
    <div class="col-12">
      <div class="user-header-bg">
        <div class="user-header">
          <div class="row align-items-center">
            <div class="col-12">
              <div class="row">
                <div class="col-12">
                  <h2 class="text-primary mb-3"> <%= current_user.name %> </h2>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <a href="<%= edit_profile_path %>" class="btn btn-primary btn-lg mt-2 px-4">Edit Profile</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="p-50 bg-white user-body">
        <div class="row mb-3 mb-md-0 align-items-center">
          <div class="col-md-6 text-md-left text-center">
            <h3 class="font-weight-bold mb-0">Information</h3>
          </div>
          <div class="col-md-6 text-md-right text-center">
          </div>
        </div>
        <div class="row row-user-fields">
          <div class="col-md-6 my-4">
            <div class="user-fields mb-3 mb-md-0">
              <span class="font-weight-bold">Name:</span>
              <span class="float-right"><%= current_user.name %></span>
            </div>
          </div>
          <div class="col-md-6 my-4">
            <div class="user-fields mb-3 mb-md-0">
              <span class="font-weight-bold">Email:</span>
              <span class="float-right"><%= current_user.email %></span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>