config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :companies
  resources :cash_transactions, only: %i[create destroy]

  get 'profile', to: 'user_panel#profile', as: :profile
  get '/edit_profile', to: 'user_panel#edit_profile', as: :edit_profile
  devise_for :users,
             controllers: { sessions: 'users/sessions',
                            registrations: 'users/registrations',
                            passwords: 'users/passwords',
                            invitations: 'users/invitations' }
  resources :users, only: %i[edit update]

  authenticated :user, ->(user) { user.has_role? :teacher } do
    root 'user_panel#profile'
  end

  authenticated :user, ->(user) { user.has_role? :student } do
    root 'companies#index'
  end
  devise_scope :user do
    root to: 'users/sessions#new'
  end
end

app/views/layouts/_footer.html.erb
<div class="footer-bg-color">
	<% if !user_signed_in? %>
	<div class="container footer-large">
		<div class="row">
			<div class="col-md-4 footer-des">
				<img src="/logo.png" width="170">
				<p class="text-left mt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
				<p class="mb-0">Social Links:
					<a href="https://facebook.com">
						<i class="fab fa-facebook-f mx-2"></i>
					</a>
					<a href="https://twitter.com">
						<i class="fab fa-twitter mx-2"></i>
					</a>
					<a href="https://instagram.com">
						<i class="fab fa-instagram mx-2"></i>
					</a>
					<a href="https://pinterest.com">
						<i class="fab fa-pinterest-p mx-2"></i>
					</a>
				</p>
			</div>
			<div class="col-md-8">
				<div class="row">
					<div class="col-sm-4 col-6 mt-4 mt-md-0">
						<h4 class="mb-3">SERVICES</h3>
						<a href="#" >Lorem ipsum</a><br>
						<a href="#" >Lorem ipsum</a><br>
						<a href="#" >Lorem ipsum</a><br>
						<a href="#" >Lorem ipsum</a>
					</div>
					<div class="col-sm-4 col-6 mt-4 mt-md-0">
						<h4 class="mb-3">SUPPORT</h3>
						<a href="#" >Lorem ipsum</a><br>
						<a href="#" >Lorem ipsum</a><br/>
						<a href="#" >Lorem ipsum</a><br/>
						<a href="#" >Lorem ipsum</a>
					</div>
					<div class="col-sm-4 col-6 mt-4 mt-md-0">
						<h4 class="mb-3">GET IN TOUCH</h3>
						<a href="#" >Lorem ipsum</a><br>
						<a href="#" >Lorem ipsum</a><br/>
						<a href="#" >Lorem ipsum</a><br/>
						<a href="#" >Lorem ipsum</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<hr class="my-0">
	<% end %>
	<div class="footer-small">
		<p class="mb-0 text-center">Cash Management System © 2020 - All rights reserved | Developed By<a href="https://systemplus.com.pk" > System Plus</a> </p>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-icon-top navbar-expand-lg">
  <div class="container">
    <a class="navbar-brand py-0" href="<%= root_path %>"><img src="/logo.png" width="220"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"><i class="fas fa-bars"></i></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if can? :manage, Company %>
          <li class="nav-item">
            <a class="nav-link" href="<%= companies_path %>">Companies</a>
          </li>
        <% end %>
        <% unless user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal"><i class="fas fa-sign-in-alt mr-1"></i> SIGN IN</a>
          </li>
          <li class="nav-item">
            <a class="nav-link btn btn-primary text-white px-1 py-2" href="<%= new_user_registration_path %>" data-toggle="modal" data-target="#signupModal"><i class="fas fa-user mr-1"></i> SIGN UP</a>
          </li>
        <% else %>
          <div class="dropdown">
            <li class="nav-item">
              <a data-target="#navbarDropdown" href="#" class="dropdown-toggle nav-link btn btn-primary px-1 py-2" data-toggle="dropdown"> <i class="fas fa-user mr-1"></i>
                <% if current_user.name.present? %>
                  <%= current_user.name %>
                <% else %>
                  <%= current_user.email %>
                <% end %>
                <i class="fas fa-chevron-down ml-1 down-arrow"></i></a>
              <div class="dropdown-menu bg-white p-0" id="navbarDropdown">
                  <a class="dropdown-item" href="<%= profile_path %>"><i class="fas fa-user-cog"></i> Profile</a>
                  <a class="dropdown-item" href="<%= edit_user_registration_path %>"><i class="fas fa-cogs"></i> Settings</a>
                  <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="delete"><i class="fas fa-sign-out-alt"></i>Log out</a>
              </div>
            </li>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<%= render 'layouts/login_modal' %>
<%= render 'layouts/signup_modal' %>

app/views/layouts/_login_modal.html.erb
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-login" role="document">
    <div class="modal-content">
      <div class="modal-header d-block">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title text-center" id="exampleModalLabel">Login to Cash Management System</h3>
      </div>
      <div class="modal-body modal-login-body">
        <%= form_for(:user, :url => session_path(:user)) do |f| %>
          <a href="#">
            <div class="loginmodal-fb mb-2">Login with Facebook</div>
          </a>
          <a href="#">
            <div class="loginmodal-google mb-2"> Login with Google</div>
          </a>
          <div class="row">
            <div class="col-5"><hr class="hr-or"></div>
            <div class="col-2"><p class="text-center mb-0 lh-35">OR</p></div>
            <div class="col-5"><hr class="hr-or"></div>
          </div>
          <div class="form-group">
            <%= f.email_field :email, autofocus: true, autocomplete: "email",placeholder: 'Enter Your Email', class: 'form-control login-form',id: "login-email", required: true %>
          </div>
          <div class="form-group">
            <%= f.password_field :password, autocomplete: "off", placeholder: 'Enter Your Password', class: 'form-control login-form',id: "login-password", required: true, minlength: 6 %>
          </div>
          <div class="form-group remember_me">
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me %>
          </div>
          <div class="actions mt-3">
            <%= f.submit "Login", class: 'btn btn-primary btn-lg btn-block mb-3 btn-submit' %>
          </div>
        <% end %>
        <center><a href="/users/password/new">Forgot your password?</a></center>
      </div>
      <div class="modal-footer d-block">
        <center>Not a member? <a href="" data-toggle="modal" data-target="#signupModal" data-dismiss="modal">Join Now</a></center>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_signup_modal.html.erb
<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-login" role="document">
    <div class="modal-content">
      <div class="modal-header d-block">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title text-center" id="exampleModalLabel">Join Cash Management System</h3>
      </div>
      <div class="modal-body modal-login-body">
        <%= form_for(:user, :url => registration_path(:user)) do |f| %>
          <div class="form-group">
            <%= f.select :role, options_for_select([['Student', 'student'], ['Teacher','teacher']]),{include_blank: 'Join as'},{ required: true, class: 'form-control'} %>
          </div>
          <div class="form-group">
            <%= f.text_field :name, autocomplete: 'off' ,required: true, placeholder: 'Enter Your Name', class: 'form-control login-form',id: "join-name" %>
          </div>
          <div class="form-group">
            <%= f.email_field :email, autocomplete: "email",placeholder: 'Enter Your Email', class: 'form-control login-form',id: "join-email", required: true %>
          </div>
          <div class="form-group">
            <%= f.password_field :password, autocomplete: "off",required: true, placeholder: 'Enter Your Password', class: 'form-control login-form',id: "join-password", minlength: 6 %>
          </div>
          <div class="form-group">
            <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: 'Enter Your Password Again',id: "join-password-again", class: 'form-control login-form', required: true, minlength: 6 %>
          </div>
          <div class="actions mt-3">
            <%= f.submit "Sign Up", class: 'btn btn-primary btn-lg btn-block mb-1 btn-submit' %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer d-block">
        <center>Already a member? <a href="#" data-toggle="modal" data-target="#loginModal" data-dismiss="modal">Login</a></center>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_swal.html.erb
<% if notice %>
  <!--<div class="alert alert-info" role="alert">-->
  <!--  <strong>Info!</strong> <%#= notice || alert %>-->
  <!--</div>-->
  <script>
    swal({
      title: 'Success',
      text: "<%= notice.html_safe %>",
      type: 'success',
      timer: 3000
    });
  </script>
<% end %>
<% if alert.present? %>
  <script>
    swal({
      title: 'Oops!',
      text: "<%= alert.html_safe %>",
      type: 'error'
    });
  </script>
<% end %>
<% if flash[:warning] %>
  <script>
    swal({
      title: 'Oops!',
      text: "<%= flash[:warning].html_safe %>",
      type: 'warning'
    });
  </script>
<% end %>
<% if flash[:info].present? %>
  <script>
    swal({
      title: 'Success',
      text: "<%= flash[:info].html_safe %>",
      type: 'success'
    });
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cash Management System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="/fevicon.jpg" type="image/jpg" sizes="16x16">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>
    <script src="https://js.stripe.com/v3/"></script>
  </head>
  <body>
    <% if user_signed_in? and current_user.has_role? :admin %>
      <%= render 'layouts/swal' %>
      <div class="container-fluid pl-0 pr-0 pr-md-15 container-main-admin">
        <div class="row">
          <div class="col-xl-2 col-md-3 pr-0 admincol-1">
            <%= render 'layouts/admin_sidebar' %>
          </div>
          <div class="col-xl-10 col-md-9 px-0 admincol-2">
            <div class="container-fluid pl-3 pl-sm-0 pr-0 pr-md-3">
              <div class="container-main-footer">
                <%= render 'layouts/header-dashboard' %>
                <%= yield %>
              </div>
            </div>
            <%= render 'layouts/admin_footer' %>
          </div>
        </div>
      </div>
    <% else %>
      <%= render 'layouts/header' %>
      <%= render 'layouts/swal' %>
      <div class="<%= user_signed_in? ? 'container-main-sign container mt-5' : 'container-main' %>" >
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    <% end %>
  </body>
</html>